spring:
  rabbitmq:
    host: amqp-cn-7pp2662qb00m.mq-amqp.cn-beijing-327844-a.aliyuncs.com
    username: LTAI5tD9KkC5bjoW9mgXsWPw
    password: eq2ZCGUEGdfndFjTIZkkkrdIkPRHvs
    virtual-host: zl-course