aliyun:
  oss:
    accessKey: #
    accessKeySecret: #
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: 'edu-stream001'


server:
  port: 8002
  servlet:
    context-path: /ossservice

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  application:
    name: SERVICE-OSS