server:
  port: 8005
spring:
  application:
    name: SERVICE-GATEWAY
  cloud:
    gateway:
      routes:
       # 用户登陆服务和权限服务
        - id: zl-acl
          uri: http://localhost:8001
          predicates:
            - Path=/aclservice/**
        # 课程服务
        - id: zl-course
          uri: http://localhost:8003
          predicates:
            - Path=/courseservice/**
