server:
  port: 8003
  servlet:
    context-path: /courseservice

spring:
  application:
    name: SERVICE-COURSE
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/courseplatform?serverTimezone=GMT%2B8
    username: root
    password: '0922'
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: locahost
    port: 6379
    lettuce:
      pool:
        min-idle: 3

mybatis-plus:
  configuration:
    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
