server:
  port: 8003
  servlet:
    context-path: /courseservice
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: SERVICE-COURSE
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.97.189.37:3306/courseplatform?serverTimezone=GMT%2B8
    username: root
    password: '123456'
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    port: 6379
    host: 39.97.189.37
    password: bywlstudio6379
  cloud:
    sentinel:
      transport:
        dashboard: 39.97.189.37:8080
        port: 8719
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  rabbitmq:
    host: amqp-cn-7pp2662qb00m.mq-amqp.cn-beijing-327844-a.aliyuncs.com
    username: LTAI5tD9KkC5bjoW9mgXsWPw
    password: eq2ZCGUEGdfndFjTIZkkkrdIkPRHvs
    virtual-host: zl-course


logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: '*'


