server:
  servlet:
    context-path: /aclservice
  port: 8001
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: SERVICE-ACL
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.97.189.37:3306/courseplatform?serverTimezone=GMT%2B8
    username: root
    password: '123456'
    initialization-mode: NEVER
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    port: 6379
    host: 39.97.189.37
    password: bywlstudio6379

  cloud:
    nacos:
      discovery:
        server-addr: 39.97.189.37:8848
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis-plus:
  configuration:
    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl
